apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: jeancossio
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: "/home/jean/espacio"
