AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC Basica - Primera infraestructura con CloudFormation'

#===================================================================
# PARAMETROS - Variables que puedes cambiar al desplegar
#===================================================================
Parameters:
  Environment:
    Description: Nombre del ambiente
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod

  VpcCIDR:
    Description: Rango de IPs para la VPC
    Type: String
    Default: 10.0.0.0/16

  PublicSubnet1CIDR:
    Description: Rango de IPs para subnet publica AZ-1
    Type: String
    Default: 10.0.1.0/24

  PublicSubnet2CIDR:
    Description: Rango de IPs para subnet publica AZ-2
    Type: String
    Default: 10.0.2.0/24

  PrivateSubnet1CIDR:
    Description: Rango de IPs para subnet privada AZ-1
    Type: String
    Default: 10.0.10.0/24

  PrivateSubnet2CIDR:
    Description: Rango de IPs para subnet privada AZ-2
    Type: String
    Default: 10.0.20.0/24

#===================================================================
# RECURSOS - Lo que se va a crear
#===================================================================
Resources:

  #-----------------------------------------------------------------
  # VPC Principal
  #-----------------------------------------------------------------
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-cf-vpc'
        - Key: Environment
          Value: !Ref Environment

  #-----------------------------------------------------------------
  # Internet Gateway - Permite acceso a internet
  #-----------------------------------------------------------------
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-igw'

  # Asociar el IGW a la VPC
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  #-----------------------------------------------------------------
  # Subnets Publicas (acceso directo a internet)
  #-----------------------------------------------------------------
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-public-subnet-1'

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: !Ref PublicSubnet2CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-public-subnet-2'

  #-----------------------------------------------------------------
  # Subnets Privadas (sin acceso directo a internet)
  #-----------------------------------------------------------------
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Ref PrivateSubnet1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-private-subnet-1'

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: !Ref PrivateSubnet2CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-private-subnet-2'

  #-----------------------------------------------------------------
  # Route Table Publica
  #-----------------------------------------------------------------
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-public-rt'

  # Ruta hacia internet
  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  # Asociar subnets publicas a la route table
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  #-----------------------------------------------------------------
  # Route Table Privada (sin ruta a internet por ahora)
  #-----------------------------------------------------------------
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-private-rt'

  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable

#===================================================================
# OUTPUTS - Valores que puedes usar despues
#===================================================================
Outputs:
  VpcId:
    Description: ID de la VPC creada
    Value: !Ref VPC
    Export:
      Name: !Sub '${Environment}-VpcId'

  PublicSubnets:
    Description: Lista de subnets publicas
    Value: !Join [',', [!Ref PublicSubnet1, !Ref PublicSubnet2]]
    Export:
      Name: !Sub '${Environment}-PublicSubnets'

  PrivateSubnets:
    Description: Lista de subnets privadas
    Value: !Join [',', [!Ref PrivateSubnet1, !Ref PrivateSubnet2]]
    Export:
      Name: !Sub '${Environment}-PrivateSubnets'