services:
  finanzas:
    build: .
    container_name: finanzas-app
    ports:
      - "1616:1616"
    volumes:
      - .:/app
      - finanzas_data:/data

  watcher:
    build: .
    container_name: finanzas-watcher
    volumes:
      - .:/app
      - finanzas_data:/data
      - D:/estados_de_cuenta/2026:/estados_de_cuenta
      - ./reportes:/reports
    command: python /app/finanzas.py
    depends_on:
      - finanzas

volumes:
  finanzas_data:
    driver: local
