apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie-nginx
  name: mealie-nginx
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie-nginx
  template:
    metadata:
      labels:
        app: mealie-nginx
    spec:
      containers:
      - image: ghcr.io/mealie-recipes/mealie:v2.7.1
        name: nginx
        ports:
          - containerPort: 9000
        volumeMounts:
          - mountPath: /app/data
            name: mealie-volume
      volumes:
        - name: mealie-volume
          persistentVolumeClaim:
            claimName: mealie-data
