apiVersion: v1
kind: Service
metadata:
  labels:
    app: mealie-nginx
  name: mealie-nginx
  namespace: mealie
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9001
  selector:
    app: mealie-nginx
  type: LoadBalancer
